# Generated by Django 2.2.8 on 2020-07-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200706_2334'),
        ('core', '0011_auto_20200708_1947'),
    ]

    operations = [
    ]
